### ISSUE TITLE
Saving error with annotated document

### ISSUE THREAD

**Issue by lakonis** [cgogolin/penandpdf#2]
I encounter saving error from time to time.
The procedure to save the file seems to go well, no error, but when trying to close the document, I am prompted with a «save?» dialog box asking to save the changes, as if the document wasn't previously saved. Answering Yes (save) or No (close without saving) has the same result : reopening the document shows no annotations. 
This error is not systematic according to the file. However, i would occurs or not with similar pdf source (coming from the same editor). I don't see a pattern in thoses files.
Thanks!
(reading on tablet Acer Iconia A3-A20, Android 4.4.2)

**Comment by cgogolin** [comment]
Thanks for your report!
I need need a bit more information to debug this.
* Which exact version of Android are you using?
* I suspect the error you describe only happens for certain storage locations. Can you try to find out whether this, for example, only happens when you save to the SD card?

Thank you very much!

On August 31, 2017 7:15:50 PM GMT+02:00, lakonis <notifications@github.com> wrote:
>I encounter saving error from time to time.
>The procedure to save the file seems to go well, no error, but when
>trying to close the document, I am prompted with a «save?» dialog box
>asking to save the changes, as if the document wasn't previously saved.
>Answering Yes (save) or No (close without saving) has the same result :
>reopening the document shows no annotations. 
>This error is not systematic according to the file. However, i would
>occurs or not with similar pdf source (coming from the same editor). I
>don't see a pattern in thoses files.
>Thanks!
>(reading on tablet Acer Iconia A3-A20, Android 4.4.2)
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgogolin/penandpdf/issues/2

-- 
Christian Gogolin
http://www.cgogolin.de

**Comment by cgogolin** [comment]
Only now saw that you already did put the android version in your question. Sorry...

On August 31, 2017 7:15:50 PM GMT+02:00, lakonis <notifications@github.com> wrote:
>I encounter saving error from time to time.
>The procedure to save the file seems to go well, no error, but when
>trying to close the document, I am prompted with a «save?» dialog box
>asking to save the changes, as if the document wasn't previously saved.
>Answering Yes (save) or No (close without saving) has the same result :
>reopening the document shows no annotations. 
>This error is not systematic according to the file. However, i would
>occurs or not with similar pdf source (coming from the same editor). I
>don't see a pattern in thoses files.
>Thanks!
>(reading on tablet Acer Iconia A3-A20, Android 4.4.2)
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgogolin/penandpdf/issues/2

-- 
Christian Gogolin
http://www.cgogolin.de

**Comment by lakonis** [comment]
Thanks,
I'll check whether saving on SD or local storage makes a difference.

**Comment by lakonis** [comment]
With some delay, hoping this can help. I don't really see the logic inside :

* :no_mouth:  From internal to internal storage, saving with same name didn't save.
* :no_mouth:  From internal to internal storage, saving with a new name didn't save.
* :no_mouth:  From internal storage to SDCARD, saving with same name didn't save.
* :dart:   From internal storage to SDCARD, saving with new name did save.
* :no_mouth:  From SDCARD to SDCARD, saving with a new or same name didn't save.

**Comment by cgogolin** [comment]
Very mysterious indeed. I looked through the code again and think that all possible errors should be handled in a way that should result in some visible feedback or in the very least they should crash the app ;-). If it would only fail for saving to the SDCARD then I would suspect some problem with the storage access framework, but like this? Especially, it shouldn't make any difference where the file was opened from. Have you ever experienced a similar problem with any other app? How much free space have you left on the device and the card? Do you have encryption enabled?

**Comment by cgogolin** [comment]
I have just released v1.3.1 on the Play Store with some improvements in the code that is responsible for saving files. Could you check whether the problems you described still occur? Thank you!

**Comment by lakonis** [comment]
Thanks! just tested and it works fine. It looks like the issue can be closed.
