### ISSUE TITLE
Alternative download source

### ISSUE THREAD

**Issue by IzzySoft** [cgogolin/penandpdf#5]
Would you mind making the `.apk` available here at Github (e.g. attaching it to `releases/`), so folks without playstore get a chance to grab it? I'd offer to serve it via [my repo](https://apt.izzysoft.de/fdroid) then (updates included as long as you provide the APKs). Thanks in advance!

**Comment by cgogolin** [comment]
Wouldn't it be more appropriate to directly apply for inclusion into the [official F-Droid repository](https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md)? I have never set up an app for inclusion there and don't have the time to do it at the moment, but would be happy if someone would do it. Including the compiled akp in the source code repository doesn't sound like a good idea to me.

**Comment by IzzySoft** [comment]
@cgogolin Sure that would be the prefered way. If you're sure you meet their [inclusion citeria](https://f-droid.org/wiki/page/Inclusion_Policy) I gladly file an RFP (Request For Packaging). As for the APK, I didn't mean to include it with the *source*, but rather to attach it to the `releases/` – see [Creating Releases](https://help.github.com/articles/creating-releases/) in the GitHub Help.

You could also decide to do the two in parallel: including it into my repo can be done immediately as soon as you've attached an APK. With the official repo, it usually takes a few weeks. Once your app is well established in the latter, I can remove it from mine again.

**Comment by cgogolin** [comment]
Ah, sorry I misunderstood. I am tagging the releases but haven't looked into attaching binaries, and frankly wasn't even aware of the possibility. I will look into it.

The only critical thing concerning the release criteria are the third party libraries. These I will have to check.

On 12 December 2017 22:34:46 CET, Izzy <notifications@github.com> wrote:
>@cgogolin Sure that would be the prefered way. If you're sure you meet
>their [inclusion
>citeria](https://f-droid.org/wiki/page/Inclusion_Policy) I gladly file
>an RFP (Request For Packaging). As for the APK, I didn't mean to
>include it with the *source*, but rather to attach it to the
>`releases/` – see [Creating
>Releases](https://help.github.com/articles/creating-releases/) in the
>GitHub Help.
>
>You could also decide to do the two in parallel: including it into my
>repo can be done immediately as soon as you've attached an APK. With
>the official repo, it usually takes a few weeks. Once your app is well
>established in the latter, I can remove it from mine again.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgogolin/penandpdf/issues/5#issuecomment-351201946

-- 
Christian Gogolin
http://www.cgogolin.de

**Comment by IzzySoft** [comment]
Yeah, those might be an issue. As far as I understand, there are "trusted repositories" for them, from which F-Droids accepts them (sources, again). Just let me know when you've checked and want me to file an RFP, I gladly assist.

**Comment by cgogolin** [comment]
Hi! I have just released 1.3.4, which fixes several bugs present in 1.3.3 and also attached the apk to the respective [releas](https://github.com/cgogolin/penandpdf/releases). Feel free to distribute this via your repository.

**Comment by IzzySoft** [comment]
OK, thanks – and [here you go](https://apt.izzysoft.de/fdroid/index/apk/com.cgogolin.penandpdf). Please check and follow the "Notif" link there, it seems ClamAV is not quite happy with it (not saying it is right, but you might wish to investigate; usual suspects are the frameworks used, often an update helps).

**Comment by cgogolin** [comment]
Awesome! The app is not using any framework, just a few third party libraries. Not all of them are up to date currently. Probably I will not have time to work on this before the beginning of 2018...

**Comment by IzzySoft** [comment]
Sure, take your time. As I've said, I count that a "false positive" (just 1 of 63 got triggered), which is why the page shows it as "notice" (would be a "warning" with 2-4 and an alert with 5+ scanners reporting something). The solution most likely is as simple as bringing those 3rd parties up-to-date. You could do that one by one, each time uploading the APK there to see if the alert is gone (so you know which one was the culprit). Once clean, please attach it to a new release (so my auto-updater picks it automatically).

Meanwhile, I might simply trigger a rescan. Wouldn't be the first time the issue solved itself after a while due to "updated signatures" on their end :wink:

Lets leave this issue open as reminder for that until the VT stuff is solved, shall we?

**Comment by cgogolin** [comment]
Yes. I will come back to you....

**Comment by dsteuer** [comment]
@IzzySoft @cgogolin Many thx to both of you! Didn't find it in the playstore when I looked for something like this some time ago, got it from izzysoft yesterday and am amazed! Great tool!

**Comment by IzzySoft** [comment]
@dsteuer thanks for the encouraging feedback! Please spread the word on both, Christian's app and my repo :wink:

Btw: Next to my repo, there are also my app listings which might help you finding things. Pen&PDF e.g. can be [found here](https://android.izzysoft.de/applists/category/named/office_pdf) as well.

**Comment by IzzySoft** [comment]
Just wondering: the last two releases have no `.apk` attached (hence no updates in my repo). Forgotten, or incidentally skipped?

**Comment by cgogolin** [comment]
Thanks for letting me know! Something with the upload seems to have gone wrong. Github displays a small red triangle next to the file, when I edit the release. I have now uploaded the files again. Hope they are now visible.

**Comment by IzzySoft** [comment]
Sorry for the late response (didn't get the notification due to temporary problems with mail). Yes, my auto-updater was able to grab the APK – so thanks a lot!
